version: '3'

services:
  stalk_activity_mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=stalk_activity
    ports:
      - "3307:3306"
  
  stalk_member_mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=stalk_member
    ports:
      - "3306:3306"

  stalk_redis:
    image: redis:latest
    ports:
      - "6379:6379"

  stalk_rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=local
      - RABBITMQ_DEFAULT_PASS=local

